name: hoomd-dev
channels:
  - conda-forge
dependencies:
  - cereal=1.3.0
  - cmake=3.19.6
  - eigen=3.3.9
  - gsd=2.4.0
  - ninja=1.10.2
  - openmpi=4.1.0
  - python=3.8.8
  - pybind11=2.6.2
  - tbb=2020.2
  - tbb-devel=2020.2
  - pytest=6.2.2
  - numpy=1.20.1
