name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2

  pre-commit-cpp:
    runs-on: ubuntu-latest
    container:
      image: glotzerlab/ci:2021.03-clang10_py38
      options: -u 0
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.2
      with:
        extra_args: -c .pre-commit-config-cpp.yaml
