name: Style check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  # Trigger on pull requests.
  pull_request:

  # Trigger on pushes to the mainline branches. This prevents building commits
  # twice when the pull request source branch is in the same repository.
  push:
    branches:
    - "master"
    - "maint"

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-python@v2.2.2
    - uses: pre-commit/action@v2.0.3
      with:
        # TODO: Run only clang-format once we can start using pre-commit.ci for the other checks
        # extra_args: --all-files --hook-stage manual clang-format
        extra_args: --all-files --hook-stage manual

  # This job is used to provide a single requirement for branch merge conditions.
  checks_complete:
    name: Style check
    needs: [pre-commit]
    runs-on: ubuntu-latest

    steps:
    - run: echo "Done!"
